# Generated by Django 4.1.2 on 2022-11-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mathoperate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MathOperate',
        ),
    ]
